---
services:
  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      # - ELASTIC_PASSWORD=testing
    networks:
      - elastic
    ports:
      - "9200:9200"
  kibana:
    image: kibana:8.17.0
    container_name: kibana_container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_container:9200
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=testing
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge